Task3 - Build a containerized FastAPI app
halvgaard/DataScience pull request #12
Opened 2022-03-18 11:11 UTC by lukyrasocha

Contains also a short tutorial on how to rerun this experiment

2022-03-18 11:43 UTC, halvgaard commented
Make sure the docker file commands are optimized for fast docker build caching. Order of commands is not optimal right now. Also pip has a flag to avoid caching (no need inside a onetime container) inside a container. 
But can't you install using poetry instead of pip?

2022-03-24 09:14 UTC, lukyrasocha commented
#12

2022-03-24 12:07 UTC, halvgaard requested changes
Why is src outside the helloworld module? 
Do people still use src as a name in python (poetry) packages - what is best practice? 
ReadMe must have run and setup instructions.

2022-03-24 12:07 UTC, halvgaard commented on Task6/helloworld/pyproject.toml
> +python = "^3.9"
python 3.9?

2022-03-24 13:15 UTC, lukyrasocha commented on Task6/helloworld/pyproject.toml
> +python = "^3.9"
Fixed to 3.7 now

2022-03-24 13:15 UTC, lukyrasocha commented
Updated everything mentioned in your previous comment.

2022-03-24 13:24 UTC, halvgaard requested changes

2022-03-24 13:24 UTC, halvgaard commented on Task6/helloworld/tests/test_helloworld.py
> +
We need a unit test of the app method. Hint: use TestClient https://fastapi.tiangolo.com/tutorial/testing/

2022-03-24 13:24 UTC, halvgaard commented on Task6/helloworld/Dockerfile
> +RUN python -m venv /venv
Why do you need a separate virtual env inside the container?

2022-03-24 13:58 UTC, lukyrasocha commented
Updated based on the last comment

2022-03-24 13:59 UTC, halvgaard approved these changes

2022-03-24 13:59 UTC, merged